/*
 * This Java source file was generated by the Gradle 'init' task.

 */

package com.dt.rts.ladmv.application;

import java.io.IOException;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.context.embedded.LocalServerPort;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.http.HttpHeaders;
import org.springframework.oxm.jaxb.Jaxb2Marshaller;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.util.ClassUtils;
import org.springframework.ws.client.core.WebServiceTemplate;
import org.springframework.ws.context.MessageContext;

import com.dt.rts.ladmv.repository.VehicleInquiryRepository;
import com.dt.rts.ladmv.services.inquiries.commoninquiryelements.VMInquiryTypeEnum;
import com.dt.rts.ladmv.services.inquiries.vehicleinquiry.InquiryRequest;
import com.dt.rts.ladmv.services.inquiries.vehicleinquiry.InquiryResponse;
import com.dt.rts.ladmv.services.inquiries.vehicleinquiry.VehicleInquiryRequest;
import com.dt.rts.ladmv.services.inquiries.vehicleinquiry.VehicleInquiryResponse;


@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
public class LASoapServiceTest {
	
	
	
	private Jaxb2Marshaller marshaller = new Jaxb2Marshaller();
	MessageContext context = null;

	TestRestTemplate restTemplate = new TestRestTemplate();
	HttpHeaders headers = new HttpHeaders();
	@LocalServerPort
	private int port = 8888;

	@Before
	public void init() throws Exception {
		marshaller.setPackagesToScan(ClassUtils.getPackageName(VehicleInquiryRequest.class));
		marshaller.afterPropertiesSet();
	}

	@Test 
	public void VMTestService() throws IOException {
		WebServiceTemplate ws = new WebServiceTemplate(marshaller);
		
		
		VehicleInquiryRequest request = new VehicleInquiryRequest();
		VehicleInquiryResponse response = new VehicleInquiryResponse();
		InquiryResponse inqResponse = new InquiryResponse();
		
		InquiryRequest inq = new InquiryRequest();
		inq.setVin("1C3CDZAB7DN529738");
		inq.setInquiryType(VMInquiryTypeEnum.valueOf("VM"));
		request.setInquiry(inq);
		request.setAuthHeader(null);
		
		
		/*System.out.println("value is "+ws.marshalSendAndReceive("http://localhost:"
				+ port + "/la", request));*/
		
		JAXBContext contextObj;
		try {
			contextObj = JAXBContext.newInstance(VehicleInquiryRequest.class);
			Marshaller marshallerObj = contextObj.createMarshaller(); 
			marshallerObj.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true); 
			
			System.out.println("Soap XML Request  - VM" );
			System.out.println("----------------------------------------------" + request );
			marshallerObj.marshal(request, System.out);
			
			contextObj = JAXBContext.newInstance(VehicleInquiryResponse.class);
			marshallerObj = contextObj.createMarshaller(); 
			
			VehicleInquiryRepository repository = new VehicleInquiryRepository();
			if("VM".equalsIgnoreCase(request.getInquiry().getInquiryType().toString())){
				response.setInquiry(repository.findVMInquirResponse(request.getInquiry().getVin().toString()));
			} else {
				response.setInquiry(repository.findLMInquirResponse(request.getInquiry().getPlateNum().toString(), request.getInquiry().getRegExpYear().toString()));
			}
			marshallerObj.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, false);  
			
			System.out.println("Soap XML Response  - VM" );
			System.out.println("===================================================" + response);
			marshallerObj.marshal(response, System.out);
			
			
		} catch (JAXBException e) {
			e.printStackTrace();
		}  
	}
	
	@Test 
	public void LMTestService() throws IOException {
		WebServiceTemplate ws = new WebServiceTemplate(marshaller);
		
		VehicleInquiryRequest request = new VehicleInquiryRequest();
		VehicleInquiryResponse response = new VehicleInquiryResponse();
		InquiryResponse inqResponse = new InquiryResponse();
		
		InquiryRequest inq = new InquiryRequest();
		inq.setInquiryType(VMInquiryTypeEnum.fromValue("LM"));
		inq.setPlateNum("ABC1234");
		inq.setRegExpYear(Integer.parseInt("0219"));
		request.setInquiry(inq);
		
		
		/*System.out.println("value is "+ws.marshalSendAndReceive("http://localhost:"
				+ port + "/la", request));*/
		
		JAXBContext contextObj;
		try {
			contextObj = JAXBContext.newInstance(VehicleInquiryRequest.class);
			Marshaller marshallerObj = contextObj.createMarshaller(); 
			marshallerObj.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true); 
			
			System.out.println("Soap XML Request  - LM" );
			System.out.println("----------------------------------------------" + request);
			marshallerObj.marshal(request, System.out);
			
			contextObj = JAXBContext.newInstance(VehicleInquiryResponse.class);
			marshallerObj = contextObj.createMarshaller(); 
			
			VehicleInquiryRepository repository = new VehicleInquiryRepository();
			if("VM".equalsIgnoreCase(request.getInquiry().getInquiryType().toString())){
				response.setInquiry(repository.findVMInquirResponse(request.getInquiry().getVin().toString()));
			} else {
				response.setInquiry(repository.findLMInquirResponse(request.getInquiry().getPlateNum().toString(), request.getInquiry().getRegExpYear().toString()));
			}
//			response.setInquiry(inqResponse);
			marshallerObj.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);  
			
			System.out.println("Soap XML Response  - LM" );
			System.out.println("===================================================" + response );
			marshallerObj.marshal(response, System.out);
			
			
		} catch (JAXBException e) {
			e.printStackTrace();
		}  
		  
	     

	}
}